[workspace]
# Applies to diplomat-core, diplomat, and diplomat-runtime
# Diplomat-tool has no MSRV for now
resolver = "2"
members = [
  "core",
  "macro",
  "runtime",
  "tool",
  "example",
  "feature_tests",
]

[workspace.package]
rust-version = "1.71"
